version: 2.0

jobs:
  archlinux:
    docker:
      - image: archlinux/base:latest
    environment:
      LANG: C
      DISPLAY: :10
      G_MESSAGES_DEBUG: pulseeffects
    steps:
      - checkout
      - run: mkdir -p pacman_cache && pacman -Sy --noconfirm && pacman -S tar --noconfirm
      - restore_cache:
          keys:
            - v1-pacman-cache
      - run: |
          pacman -Su --cachedir pacman_cache --noconfirm
          pacman -S --cachedir pacman_cache --noconfirm pkg-config git gcc meson itstool boost appstream-glib gettext gtk3 gtkmm3 glibmm pulseaudio gstreamer gst-plugins-good gst-plugins-bad boost-libs libsigc++ libsndfile libsamplerate zita-convolver libebur128 lilv calf zam-plugins rubberband mda.lv2 lsp-plugins xorg-server-xvfb
          pacman -Sc --cachedir pacman_cache --noconfirm
      - save_cache:
          key: pacman-cache
          paths:
            - pacman_cache
      - run:
          name: Starting dbus
          command: echo 'export $(dbus-launch)' >> $BASH_ENV
          background: true
      - run:
          name: Starting Xvfb
          command: Xvfb $DISPLAY -screen 0 1280x1024x24
          background: true
      - run:
          name: Starting Pulseaudio
          command: |
                pulseaudio -D --exit-idle-time=-1
                pactl load-module module-null-sink sink_name=DummyOutput
                pactl load-module module-null-source source_name=DummyInput
                pacmd set-default-source DummyInput
                pacmd set-default-sink DummyOutput
                pactl list sinks
                pactl list sources
      # build PulseEffects
      - run: meson build && cd build && ninja -j 1 && ninja -j 1 install
      - run:
          name: Starting a GStreamer pipeline
          command: gst-launch-1.0 -v audiotestsrc ! queue ! pulsesink
          background: true
      - run:
          name: Running PulseEffects
          command: |
                sleep 10
                pulseeffects --gapplication-service &
                sleep 10
                echo "open PE window"
                pulseeffects
                sleep 10
                echo "finish PE process"
                pulseeffects -q || true

workflows:
  version: 2
  build:
    jobs:
      - archlinux
