version: 2.0

jobs:
  archlinux:
    docker:
      - image: archlinux/base:latest
    environment:
      LANG: C
      DISPLAY: :10
      G_MESSAGES_DEBUG: pulseeffects
    steps:
      - run: mkdir -p pacman_cache && pacman -Sy --noconfirm && pacman -S tar --noconfirm
      - restore_cache:
          keys:
            - pacman-cache
      - run: |
          pacman -Su --noconfirm --cachedir pacman_cache
          pacman -S --cachedir pacman_cache --noconfirm pkg-config git gcc meson itstool boost appstream-glib gettext gtk3 gtkmm3 glibmm pulseaudio gstreamer gst-plugins-good gst-plugins-bad boost-libs libsigc++ libsndfile libsamplerate zita-convolver libebur128 lilv calf zam-plugins rubberband mda.lv2 lsp-plugins xorg-server-xvfb
          pacman -Sc --cachedir pacman_cache --noconfirm
      - save_cache:
          key: pacman-cache
          paths:
            - pacman_cache
      - run:
          name: Starting dbus
          command: echo 'export $(dbus-launch)' >> $BASH_ENV
          background: true
      - run:
          name: Starting Xvfb
          command: Xvfb $DISPLAY -screen 0 1280x1024x24
          background: true
      - checkout
      # start Pulseaudio with virtual sink and source
      - run: .circleci/start_pulseaudio.sh
      # build PulseEffects
      - run: meson build && cd build && ninja -j 1 && ninja -j 1 install
      - run:
          name: Starting a GStreamer pipeline
          command: gst-launch-1.0 -v audiotestsrc ! queue ! pulsesink
          background: true
      - run: sleep 10
      - run:
          name: Starting PE service
          command: pulseeffects --gapplication-service
          background: true
      - run: sleep 10

workflows:
  version: 2
  build:
    jobs:
      - archlinux
