version: 2.0

jobs:
  archlinux:
    docker:
      - image: archlinux/base:latest
    environment:
      LANG: C
      DISPLAY: :10
      G_MESSAGES_DEBUG: pulseeffects
    steps:
      - checkout
      - run:
          name: Starting dbus
          command: echo 'export $(dbus-launch)' >> $BASH_ENV
          background: true
      - run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm pkg-config git gcc meson itstool boost appstream-glib gettext gtk3 gtkmm3 glibmm pulseaudio gstreamer gst-plugins-good gst-plugins-bad boost-libs libsigc++ libsndfile libsamplerate zita-convolver libebur128 lilv calf zam-plugins rubberband mda.lv2 lsp-plugins xorg-server-xvfb
      - run:
          name: Starting Xvfb
          command: Xvfb $DISPLAY -screen 0 1920x1080x24
          background: true
      # start Pulseaudio with virtual sink and source
      - run: .circleci/start_pulseaudio.sh
      # build PulseEffects
      - run: meson build && cd build && ninja -j 1 && ninja -j 1 install
      - run:
          name: Starting PE service
          command: pulseeffects --gapplication-service
          background: true
      - run:
          name: Open PE window
          command: pulseeffects
          background: true
      # finish PE
      - run: pulseeffects -q

workflows:
  version: 2
  build:
    jobs:
      - archlinux
