version: 2.0

jobs:
  archlinux:
    docker:
      - image: archlinux/base:latest
    environment:
      LANG: C
      DISPLAY: :10
      G_MESSAGES_DEBUG: pulseeffects
    steps:
      - checkout
      - run: mkdir -p pacman_cache && pacman -Sy --noconfirm && pacman -S tar --noconfirm
      - run: pacman -Sc --noconfirm
      - restore_cache:
          keys:
            - pacman-cache
      - run: |
          if [ "$(ls -A pacman_cache)" ]
          then
             cp -v pacman_cache/* /var/cache/pacman/pkg/
          fi
      - run: |
          pacman -Su --noconfirm
          pacman -S --noconfirm pkg-config git gcc meson itstool boost appstream-glib gettext gtk3 gtkmm3 glibmm pulseaudio gstreamer gst-plugins-good gst-plugins-bad boost-libs libsigc++ libsndfile libsamplerate zita-convolver libebur128 lilv calf zam-plugins rubberband mda.lv2 lsp-plugins xorg-server-xvfb
          ls /var/cache/pacman/pkg
      - run: rm -rf pacman_cache/* && cp -v /var/cache/pacman/pkg/* pacman_cache
      - save_cache:
          key: pacman-cache
          paths:
            - pacman_cache
      - run:
          name: Starting dbus
          command: echo 'export $(dbus-launch)' >> $BASH_ENV
          background: true
      - run:
          name: Starting Xvfb
          command: Xvfb $DISPLAY -screen 0 1920x1080x24
          background: true
      # start Pulseaudio with virtual sink and source
      - run: .circleci/start_pulseaudio.sh
      # build PulseEffects
      - run: meson build && cd build && ninja -j 1 && ninja -j 1 install
      - run:
          name: Starting a GStreamer pipeline
          command: gst-launch pulsesrc ! queue ! pulsesink
          background: true
      - run:
          name: Starting PE service
          command: pulseeffects --gapplication-service
          background: true

workflows:
  version: 2
  build:
    jobs:
      - archlinux
