version: 2.0

jobs:
  archlinux:
    docker:
      - image: archlinux/base:latest
    steps:
      - checkout
      - run: pacman -Syu --noconfirm && pacman -S --noconfirm bash pkg-config git gcc meson itstool boost appstream-glib gettext gtk3 gtkmm3 glibmm pulseaudio gstreamer gst-plugins-good gst-plugins-bad boost-libs libsigc++ libsndfile libsamplerate zita-convolver libebur128 lilv
      - run:
        name: Setup Environment Variables
        command: |
          echo 'export LANG="C"' >> $BASH_ENV
          echo 'export DISPLAY=":1"' >> $BASH_ENV
          echo 'export G_MESSAGES_DEBUG="pulseeffects"' >> $BASH_ENV
      # Start Xvfb in background
      - run: Xvfb :1 &
      # start Pulseaudio with virtual sink and source
      - run: .circleci/start_pulseaudio.sh
      # build PulseEffects
      - run: meson build && cd build && ninja -j 1 && ninja -j 1 install
      # start PulseEffects in service mode
      - run: pulseeffects --gapplication-service & sleep 5
      # open PE window
      - run: pulseeffects &
      # finish PE
      - run: pulseeffects -q

workflows:
  version: 2
  build:
    jobs:
      - archlinux
