version: 2.0

jobs:
  archlinux:
    docker:
      - image: archlinux/base:latest
    steps:
      - checkout
      - run: pacman -Syu --noconfirm && pacman -S --noconfirm pkg-config git gcc meson itstool boost appstream-glib gettext gtk3 gtkmm3 glibmm pulseaudio gstreamer gst-plugins-good gst-plugins-bad boost-libs libsigc++ libsndfile libsamplerate zita-convolver libebur128 lilv
      # Guarantee consistency of language strings in GUIs and CLI outputs
      - run: export LANG=C G_MESSAGES_DEBUG=pulseeffects
      # Start Xvfb in background
      - run: Xvfb :1 & export DISPLAY=:1
      # start Pulseaudio with virtual sink and source
      - run: ./util/start_pulseaudio.sh
      # build PulseEffects
      - run: meson build && cd build && ninja -j 1 && ninja -j 1 install
      # start PulseEffects in service mode
      - run: pulseeffects --gapplication-service &
      # open PE window
      - run: pulseeffects &

workflows:
  version: 2
  build:
    jobs:
      - archlinux
